#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: scripts/run_autonovelwriter_public_tmux.sh [options]

Starts AutoNovelWriter in one tmux session:
  pane 0: Tornado backend (:8788)
  pane 1: authenticated public proxy (:18080 by default)
  pane 2: ngrok tunnel to the public proxy, unless --no-ngrok is set
  pane 3: backend log tail

Options:
  --session <name>       tmux session name (default: autonovelwriter_public)
  --repo <path>          AutoNovelWriter repo path (default: script parent)
  --env-file <path>      env file with login token (default: ~/.config/autonovelwriter/public.env)
  --backend-port <n>     backend port (default: 8788)
  --public-port <n>      authenticated proxy port (default: 18080; use 80 only if permitted)
  --ngrok-url <domain>   fixed ngrok domain (default: dullish-amee-multiovulate.ngrok-free.dev)
  --conda-env <name>     conda env (default: autoappdev)
  --no-ngrok             skip the ngrok pane so an outer stack launcher can own the tunnel
  --kill                 kill existing tmux session first
  --attach               attach after starting
  -h, --help             show help

Example:
  scripts/run_autonovelwriter_public_tmux.sh --kill
USAGE
}

session="autonovelwriter_public"
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
env_file="${HOME}/.config/autonovelwriter/public.env"
backend_host="127.0.0.1"
backend_port="8788"
public_host="127.0.0.1"
public_port="18080"
ngrok_url="dullish-amee-multiovulate.ngrok-free.dev"
conda_env="autoappdev"
kill_existing=0
attach=0
start_ngrok=1

while [ $# -gt 0 ]; do
  case "$1" in
    --session) session="${2:-}"; shift 2 ;;
    --repo) repo_root="${2:-}"; shift 2 ;;
    --env-file) env_file="${2:-}"; shift 2 ;;
    --backend-port) backend_port="${2:-}"; shift 2 ;;
    --public-port) public_port="${2:-}"; shift 2 ;;
    --ngrok-url) ngrok_url="${2:-}"; shift 2 ;;
    --conda-env|--env) conda_env="${2:-}"; shift 2 ;;
    --no-ngrok) start_ngrok=0; shift ;;
    --kill|--restart) kill_existing=1; shift ;;
    --attach) attach=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage; exit 1 ;;
  esac
done

repo_root="$(cd "$repo_root" && pwd)"

if ! command -v tmux >/dev/null 2>&1; then
  echo "tmux not found in PATH." >&2
  exit 1
fi

if [ ! -f "$env_file" ]; then
  echo "Missing env file: $env_file" >&2
  echo "Create it with AUTONOVELWRITER_PUBLIC_USERNAME and AUTONOVELWRITER_PUBLIC_TOKEN." >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
. "$env_file"
set +a

if [ -z "${AUTONOVELWRITER_PUBLIC_USERNAME:-}" ] || [ -z "${AUTONOVELWRITER_PUBLIC_TOKEN:-}" ]; then
  echo "Env file must set AUTONOVELWRITER_PUBLIC_USERNAME and AUTONOVELWRITER_PUBLIC_TOKEN." >&2
  exit 1
fi

cat >"$repo_root/pwa/config.local.js" <<'EOF'
// Auto-generated by scripts/run_autonovelwriter_public_tmux.sh
// Keep API same-origin so ngrok users call /api through the authenticated proxy.
window.__AUTOAPPDEV_CONFIG__ = window.__AUTOAPPDEV_CONFIG__ || {};
window.__AUTOAPPDEV_CONFIG__.API_BASE_URL = "";
EOF

if tmux has-session -t "$session" 2>/dev/null; then
  if [ "$kill_existing" -eq 1 ]; then
    tmux kill-session -t "$session"
    sleep 1
  else
    echo "tmux session already running: $session"
    if [ "$attach" -eq 1 ]; then
      exec tmux attach -t "$session"
    fi
    exit 0
  fi
fi

if [ "$kill_existing" -eq 1 ] && [ "$start_ngrok" -eq 1 ]; then
  while IFS= read -r pid; do
    [ -n "$pid" ] && kill "$pid" 2>/dev/null || true
  done < <(pgrep -f "[n]grok http --url=${ngrok_url} ${public_port}" || true)
  sleep 1
fi

backend_cmd=(
  env
  "AUTOAPPDEV_HOST=$backend_host"
  "AUTOAPPDEV_PORT=$backend_port"
  "AUTONOVELWRITER_ENABLE_CODEX=1"
  "AUTONOVELWRITER_CODEX_REPLY_MODEL=gpt-5.5"
  "AUTONOVELWRITER_CODEX_REPLY_REASONING=medium"
  "AUTONOVELWRITER_CODEX_WRITER_MODEL=gpt-5.5"
  "AUTONOVELWRITER_CODEX_WRITER_REASONING=high"
  conda run -n "$conda_env" python -m backend.app
)

ngrok_cmd="if command -v ngrok >/dev/null 2>&1; then ngrok http --url=${ngrok_url} ${public_port}; else echo 'ngrok not found in PATH. Install/configure ngrok, then rerun this script.'; sleep infinity; fi"
log_cmd="mkdir -p \"$repo_root/runtime/logs\" && touch \"$repo_root/runtime/logs/backend.log\" && tail -n +1 -f \"$repo_root/runtime/logs/backend.log\""
proxy_cmd="set -a; . \"$env_file\"; set +a; env AUTOAPPDEV_HOST=\"$backend_host\" AUTOAPPDEV_PORT=\"$backend_port\" AUTONOVELWRITER_PUBLIC_HOST=\"$public_host\" AUTONOVELWRITER_PUBLIC_PORT=\"$public_port\" python3 scripts/autonovelwriter_public_proxy.py"

backend_pane="$(tmux new-session -d -s "$session" -c "$repo_root" -P -F "#{pane_id}" "bash")"
tmux rename-window -t "$session:0" "autonovelwriter-public"
tmux set-option -t "$session" -g mouse on

tmux send-keys -t "$backend_pane" "cd \"$repo_root\"" C-m
tmux send-keys -t "$backend_pane" "echo '[backend] http://$backend_host:$backend_port'" C-m
tmux send-keys -t "$backend_pane" "$(printf '%q ' "${backend_cmd[@]}")" C-m

proxy_pane="$(tmux split-window -h -t "$backend_pane" -c "$repo_root" -P -F "#{pane_id}" "bash")"
tmux send-keys -t "$proxy_pane" "cd \"$repo_root\"" C-m
tmux send-keys -t "$proxy_pane" "echo '[public proxy] http://$public_host:$public_port -> backend :$backend_port'" C-m
tmux send-keys -t "$proxy_pane" "$proxy_cmd" C-m

if [ "$start_ngrok" -eq 1 ]; then
  ngrok_pane="$(tmux split-window -v -t "$proxy_pane" -c "$repo_root" -P -F "#{pane_id}" "bash")"
  tmux send-keys -t "$ngrok_pane" "$ngrok_cmd" C-m
fi

log_pane="$(tmux split-window -v -t "$backend_pane" -c "$repo_root" -P -F "#{pane_id}" "bash")"
tmux send-keys -t "$log_pane" "$log_cmd" C-m

tmux select-layout -t "$session:0" tiled

echo "AutoNovelWriter public proxy: http://$public_host:$public_port"
if [ "$start_ngrok" -eq 1 ]; then
  echo "ngrok target:                 ngrok http --url=$ngrok_url $public_port"
else
  echo "ngrok target:                 disabled (--no-ngrok)"
fi
echo "tmux attach -t $session"

if [ "$attach" -eq 1 ]; then
  exec tmux attach -t "$session"
fi
