#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: scripts/run_autonovelwriter_tmux.sh [options]

Starts a tmux session for the current AutoNovelWriter layout:
  - Tornado backend (`python -m backend.app`, default :8788)
  - PWA static server (default :5173)
  - backend log tail

Options:
  --session <name>       tmux session name (default: autonovelwriter_app)
  --backend-host <ip>    backend bind host (default: 127.0.0.1)
  --backend-port <n>     backend port (default: 8788)
  --pwa-host <ip>        PWA bind host (default: 127.0.0.1)
  --pwa-port <n>         PWA port (default: 5173)
  --env <conda_env>      conda env to run under (default: autoappdev)
  --enable-codex         enable browser-triggered Codex reply/writer agents
  --skip-setup           do not run scripts/setup_autoappdev_env.sh
  --kill                 kill existing session and recreate
  --no-attach            do not attach
  -h, --help             show help

Example:
  scripts/run_autonovelwriter_tmux.sh --kill --no-attach --enable-codex
USAGE
}

session="autonovelwriter_app"
backend_host="${AUTOAPPDEV_HOST:-127.0.0.1}"
backend_port="${AUTOAPPDEV_PORT:-8788}"
pwa_host="127.0.0.1"
pwa_port="${AUTOAPPDEV_PWA_PORT:-5173}"
conda_env="autoappdev"
enable_codex=0
skip_setup=0
kill_existing=0
attach=1

while [ $# -gt 0 ]; do
  case "$1" in
    --session) session="${2:-}"; shift 2 ;;
    --backend-host|--host) backend_host="${2:-}"; shift 2 ;;
    --backend-port) backend_port="${2:-}"; shift 2 ;;
    --pwa-host) pwa_host="${2:-}"; shift 2 ;;
    --pwa-port) pwa_port="${2:-}"; shift 2 ;;
    --env) conda_env="${2:-}"; shift 2 ;;
    --enable-codex) enable_codex=1; shift ;;
    --skip-setup) skip_setup=1; shift ;;
    --kill|--restart) kill_existing=1; shift ;;
    --no-attach|--detached) attach=0; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage; exit 1 ;;
  esac
done

if ! command -v tmux >/dev/null 2>&1; then
  echo "tmux not found in PATH." >&2
  exit 1
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [ "$skip_setup" -eq 0 ] && [ -x "$repo_root/scripts/setup_autoappdev_env.sh" ]; then
  "$repo_root/scripts/setup_autoappdev_env.sh"
fi

api_host="$backend_host"
case "$api_host" in
  0.0.0.0|::|::0) api_host="127.0.0.1" ;;
esac
cat >"$repo_root/pwa/config.local.js" <<EOF
// Auto-generated by scripts/run_autonovelwriter_tmux.sh
window.__AUTOAPPDEV_CONFIG__ = window.__AUTOAPPDEV_CONFIG__ || {};
window.__AUTOAPPDEV_CONFIG__.API_BASE_URL = "http://$api_host:$backend_port";
EOF

if tmux has-session -t "$session" 2>/dev/null; then
  if [ "$kill_existing" -eq 1 ]; then
    tmux kill-session -t "$session"
  else
    if [ "$attach" -eq 1 ]; then
      exec tmux attach -t "$session"
    fi
    echo "tmux session already running: $session"
    exit 0
  fi
fi

backend_env=(
  "AUTOAPPDEV_HOST=$backend_host"
  "AUTOAPPDEV_PORT=$backend_port"
  "AUTONOVELWRITER_CODEX_REPLY_MODEL=gpt-5.5"
  "AUTONOVELWRITER_CODEX_REPLY_REASONING=medium"
  "AUTONOVELWRITER_CODEX_WRITER_MODEL=gpt-5.5"
  "AUTONOVELWRITER_CODEX_WRITER_REASONING=high"
)
if [ "$enable_codex" -eq 1 ]; then
  backend_env+=("AUTONOVELWRITER_ENABLE_CODEX=1")
fi

backend_prefix="env ${backend_env[*]}"
backend_cmd="$backend_prefix conda run -n \"$conda_env\" python -m backend.app"
pwa_cmd="python3 -m http.server \"$pwa_port\" --bind \"$pwa_host\""
log_cmd="mkdir -p \"$repo_root/runtime/logs\" && touch \"$repo_root/runtime/logs/backend.log\" && tail -n +1 -f \"$repo_root/runtime/logs/backend.log\""

tmux new-session -d -s "$session" -c "$repo_root" "bash"
tmux rename-window -t "$session:0" "autonovelwriter"
tmux set-option -t "$session" -g mouse on

tmux send-keys -t "$session:0.0" "cd \"$repo_root\"" C-m
tmux send-keys -t "$session:0.0" "echo \"[backend] http://$backend_host:$backend_port\"" C-m
if [ "$enable_codex" -eq 1 ]; then
  tmux send-keys -t "$session:0.0" "echo \"[codex] quick reply gpt-5.5 medium; assistant gpt-5.5 high\"" C-m
fi
tmux send-keys -t "$session:0.0" "$backend_cmd" C-m

tmux split-window -h -t "$session:0" -c "$repo_root/pwa" "bash"
tmux send-keys -t "$session:0.1" "cd \"$repo_root/pwa\"" C-m
tmux send-keys -t "$session:0.1" "echo \"[pwa] http://$pwa_host:$pwa_port\"" C-m
tmux send-keys -t "$session:0.1" "$pwa_cmd" C-m

tmux split-window -v -t "$session:0.1" -c "$repo_root" "bash"
tmux send-keys -t "$session:0.2" "$log_cmd" C-m

tmux select-layout -t "$session:0" tiled
echo "AutoNovelWriter backend: http://$backend_host:$backend_port"
echo "AutoNovelWriter PWA:     http://$pwa_host:$pwa_port"
echo "tmux attach -t $session"

if [ "$attach" -eq 1 ]; then
  exec tmux attach -t "$session"
fi
